param(
  [string]$AppDomain = "streamshogun.com",
  [string]$SupportEmail = "colin.kenny777@gmail.com",
  [string]$EmailFrom = "StreamShogun <no-reply@streamshogun.com>",
  [string]$ResendApiKey = "",
  [switch]$StartStack,
  [switch]$Force
)

$ErrorActionPreference = "Stop"

function New-RandomHex {
  param([int]$ByteLength)
  $bytes = New-Object byte[] $ByteLength
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
  return ([System.BitConverter]::ToString($bytes) -replace "-", "").ToLowerInvariant()
}

function Require-Docker {
  try {
    docker info | Out-Null
  } catch {
    throw "Docker Desktop needs to be running before bootstrap-local.ps1 can continue."
  }
}

$repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$dockerDir = Join-Path $repoRoot "docker"
$envPath = Join-Path $dockerDir ".env.production"

if ((Test-Path $envPath) -and -not $Force) {
  throw "docker/.env.production already exists. Re-run with -Force if you want to replace it."
}

Require-Docker

$postgresPassword = New-RandomHex -ByteLength 24
$jwtSecret = New-RandomHex -ByteLength 32
$adminKey = New-RandomHex -ByteLength 16

$lines = @(
  "# Generated by scripts/selfhost/bootstrap-local.ps1",
  "POSTGRES_PASSWORD=`"$postgresPassword`"",
  "JWT_SECRET=`"$jwtSecret`"",
  "JWT_ACCESS_TTL=`"15m`"",
  "JWT_REFRESH_TTL=`"7d`"",
  "CORS_ORIGIN=`"https://$AppDomain`"",
  "APP_PUBLIC_URL=`"https://$AppDomain`"",
  "COOKIE_DOMAIN=`".$AppDomain`"",
  "SUPPORT_EMAIL=`"$SupportEmail`"",
  "EMAIL_FROM=`"$EmailFrom`"",
  "LOG_LEVEL=`"info`"",
  "ADMIN_KEY=`"$adminKey`""
)

if ($ResendApiKey) {
  $lines += "RESEND_API_KEY=`"$ResendApiKey`""
}

Set-Content -Path $envPath -Value ($lines -join "`r`n") -Encoding UTF8

Write-Host ""
Write-Host "Created docker/.env.production with fresh local secrets." -ForegroundColor Green
Write-Host "App domain: $AppDomain"
Write-Host "Support email: $SupportEmail"

if ($StartStack) {
  Write-Host ""
  Write-Host "Starting StreamShogun containers..." -ForegroundColor Cyan
  docker compose --env-file docker/.env.production -f docker/docker-compose.production.yml up -d --build
}

Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. Point streamshogun.com, www.streamshogun.com, and api.streamshogun.com to your home public IP."
Write-Host "2. Forward router ports 80 and 443 to this PC."
Write-Host "3. If you want password reset emails later, rerun with -ResendApiKey or add RESEND_API_KEY to docker/.env.production."
Write-Host "4. Start the stack with: pnpm selfhost:up"
