services:
  postgres:
    image: postgres:15-alpine
    container_name: shogun-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: shogun
      POSTGRES_PASSWORD: shogun
      POSTGRES_DB: streamshogun
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
